[serve]
grpc_addr = "[::1]:50051"
rest_addr = "127.0.0.1:3001"

[logging]
dirs = "api=debug"

[identity_provider]
client_id = "..."
client_secret = "..."
issuer_url = "https://{{domain}}/realms/{{realm_id}}"
