[serve]
grpc_addr = "[::]:50051"
rest_addr = "0.0.0.0:3000"

[logging]
dirs = "api=info"

[identity_provider]
client_id = "..."
client_secret = "..."
issuer_url = "https://{{domain}}/realms/{{realm_id}}"
