services:
  api:
    container_name: "api"
    hostname: "api"
    restart: "unless-stopped"
    build:
      context: .
    expose:
      - 3001
    ports:
      - 127.0.0.1:$API_PORT:3001
    networks:
      - auth_service.network
    environment:
      - CONFIG_PATH=${CONFIG_PATH:-./configs/prod.toml}
    volumes:
      - ./configs:/app/configs:ro

networks:
  auth_service.network:
    external: true
