set export

host := `uname -a`

help:
    just -l

lint:
    cargo clippy --all-features -- -W clippy::pedantic

fmt:
    cargo fmt -- --check

test:
    cargo test --tests --all-features -- --test-threads 1 --nocapture

@build:
    cargo build --all-features

@build-release:
    cargo build --release --all-features

@run: build
    cargo run

@run-release: build-release
    cargo run --release

@run-dev CONFIG_PATH='./configs/dev.toml':
    just run

@run-prod CONFIG_PATH='./configs/prod.toml':
    just run

@run-dev-release CONFIG_PATH='./configs/dev.toml':
    just run-release

@run-prod-release CONFIG_PATH='./configs/prod.toml':
    just run-release

@run-docker:
    docker compose -p authorization_api up --build
